import AmbientLight from './AmbientLight';
import DirectionalLight from './DirectionalLight';
import LightItem from './LightItem';
import List from '../Utility/List';
import PointLight from './PointLight';
export declare let AmbientLights: List<AmbientLight>;
export declare let DirectionalLights: List<DirectionalLight>;
export declare let PointLights: List<PointLight>;
export declare function Add(ambientLight: AmbientLight): void;
export declare function Add(directionalLight: DirectionalLight): void;
export declare function Add(pointLight: PointLight): void;
export declare function Remove(light: LightItem): void;
