env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - 'apps'
  - 'node_modules'
  - '.github'
  - 'scripts'
  - 'packages/**/lib'
  - 'packages/**/*.js'
  - 'packages/**/*.json'
  - 'packages/**/*.tsbuildinfo'

rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
