import Cloneable from '../Interfaces/Cloneable';
import List from '../Utility/List';
import Matrix3 from './Matrix3';
import Matrix4 from './Matrix4';
export default class Matrix2 extends Float32Array implements Cloneable<Matrix2> {
    constructor();
    constructor(matrix: Matrix2);
    constructor(matrix: Matrix3);
    constructor(matrix: Matrix4);
    constructor(array: Float32Array);
    constructor(array: number[]);
    constructor(list: List<number>);
    constructor(m11: number, m12: number, m21: number, m22: number);
    M11: number;
    M12: number;
    M21: number;
    M22: number;
    static readonly ZERO: Matrix2;
    static readonly IDENTITY: Matrix2;
    Set(matrix: Matrix2): Matrix2;
    Set(matrix: Matrix3): Matrix2;
    Set(matrix: Matrix4): Matrix2;
    Set(array: Float32Array): Matrix2;
    Set(array: number[]): Matrix2;
    Set(list: List<number>): Matrix2;
    Set(m11: number, m12: number, m21: number, m22: number): Matrix2;
    static Set(matrix: Matrix2, m11: Matrix2 | Matrix3 | Matrix4 | Float32Array | number[] | List<number> | number, m12?: number, m21?: number, m22?: number): Matrix2;
    Transpose(): Matrix2;
    static Transpose(matrix: Matrix2): Matrix2;
    readonly Determinant: number;
    static Determinant(m11: Matrix2 | Float32Array | number[] | List<number> | number, m12?: number, m21?: number, m22?: number): number;
    Inverse(): Matrix2;
    static Inverse(matrix: Matrix2): Matrix2;
    Sum(matrix: Matrix2): Matrix2;
    Sum(array: Float32Array): Matrix2;
    Sum(array: number[]): Matrix2;
    Sum(list: List<number>): Matrix2;
    Sum(m11: number, m12: number, m21: number, m22: number): Matrix2;
    static Sum(matrix: Matrix2, m11: Matrix2 | Float32Array | number[] | List<number> | number, m12?: number, m21?: number, m22?: number): Matrix2;
    Mult(m11: Matrix2): Matrix2;
    Mult(array: Float32Array): Matrix2;
    Mult(array: number[]): Matrix2;
    Mult(list: List<number>): Matrix2;
    Mult(m11: number, m12: number, m21: number, m22: number): Matrix2;
    static Mult(matrix: Matrix2, m11: Matrix2 | Float32Array | number[] | List<number> | number, m12?: number, m21?: number, m22?: number): Matrix2;
    Scale(scaler: number): Matrix2;
    static Scale(matrix: Matrix2, scaler: number): Matrix2;
    Identity(): Matrix2;
    static Identity(matrix: Matrix2): Matrix2;
    Clone(): Matrix2;
    private static Destructure;
}
