import Cloneable from '../Interfaces/Cloneable';
import List from '../Utility/List';
import Matrix2 from './Matrix2';
import Matrix3 from './Matrix3';
export default class Matrix4 extends Float32Array implements Cloneable<Matrix4> {
    constructor();
    constructor(matrix: Matrix2);
    constructor(matrix: Matrix3);
    constructor(matrix: Matrix4);
    constructor(array: Float32Array);
    constructor(array: number[]);
    constructor(list: List<number>);
    constructor(m11: number, m12: number, m13: number, m14: number, m21: number, m22: number, m23: number, m24: number, m31: number, m32: number, m33: number, m34: number, m41: number, m42: number, m43: number, m44: number);
    M11: number;
    M12: number;
    M13: number;
    M14: number;
    M21: number;
    M22: number;
    M23: number;
    M24: number;
    M31: number;
    M32: number;
    M33: number;
    M34: number;
    M41: number;
    M42: number;
    M43: number;
    M44: number;
    static readonly ZERO: Matrix4;
    static readonly IDENTITY: Matrix4;
    Set(matrix: Matrix2): Matrix4;
    Set(matrix: Matrix3): Matrix4;
    Set(matrix: Matrix4): Matrix4;
    Set(array: Float32Array): Matrix4;
    Set(array: number[]): Matrix4;
    Set(list: List<number>): Matrix4;
    Set(m11: number, m12: number, m13: number, m14: number, m21: number, m22: number, m23: number, m24: number, m31: number, m32: number, m33: number, m34: number, m41: number, m42: number, m43: number, m44: number): Matrix4;
    static Set(matrix: Matrix4, m11: Matrix4 | Matrix3 | Matrix2 | Float32Array | number[] | List<number> | number, m12?: number, m13?: number, m14?: number, m21?: number, m22?: number, m23?: number, m24?: number, m31?: number, m32?: number, m33?: number, m34?: number, m41?: number, m42?: number, m43?: number, m44?: number): Matrix4;
    Transpose(): Matrix4;
    static Transpose(matrix: Matrix4): Matrix4;
    readonly Determinant: number;
    static Determinant(m11: Matrix4 | Float32Array | number[] | List<number> | number, m12?: number, m13?: number, m14?: number, m21?: number, m22?: number, m23?: number, m24?: number, m31?: number, m32?: number, m33?: number, m34?: number, m41?: number, m42?: number, m43?: number, m44?: number): number;
    Inverse(): Matrix4;
    static Inverse(matrix: Matrix4): Matrix4;
    Sum(matrix: Matrix2): Matrix4;
    Sum(matrix: Matrix3): Matrix4;
    Sum(matrix: Matrix4): Matrix4;
    Sum(array: Float32Array): Matrix4;
    Sum(array: number[]): Matrix4;
    Sum(list: List<number>): Matrix4;
    Sum(m11: number, m12: number, m13: number, m14: number, m21: number, m22: number, m23: number, m24: number, m31: number, m32: number, m33: number, m34: number, m41: number, m42: number, m43: number, m44: number): Matrix4;
    static Sum(matrix: Matrix4, m11: Matrix4 | Float32Array | number[] | List<number> | number, m12?: number, m13?: number, m14?: number, m21?: number, m22?: number, m23?: number, m24?: number, m31?: number, m32?: number, m33?: number, m34?: number, m41?: number, m42?: number, m43?: number, m44?: number): Matrix4;
    Mult(matrix: Matrix2): Matrix4;
    Mult(matrix: Matrix3): Matrix4;
    Mult(matrix: Matrix4): Matrix4;
    Mult(array: Float32Array): Matrix4;
    Mult(array: number[]): Matrix4;
    Mult(list: List<number>): Matrix4;
    Mult(m11: number, m12: number, m13: number, m14: number, m21: number, m22: number, m23: number, m24: number, m31: number, m32: number, m33: number, m34: number, m41: number, m42: number, m43: number, m44: number): Matrix4;
    static Mult(matrix: Matrix4, m11: Matrix4 | Float32Array | number[] | List<number> | number, m12?: number, m13?: number, m14?: number, m21?: number, m22?: number, m23?: number, m24?: number, m31?: number, m32?: number, m33?: number, m34?: number, m41?: number, m42?: number, m43?: number, m44?: number): Matrix4;
    Scale(scaler: number): Matrix4;
    static Scale(matrix: Matrix4, scaler: number): Matrix4;
    Identity(): Matrix4;
    static Identity(matrix: Matrix4): Matrix4;
    Clone(): Matrix4;
    private static Destructure;
}
