import Cloneable from '../Interfaces/Cloneable';
import List from '../Utility/List';
import Vector2 from './Vector2';
import Vector3 from './Vector3';
export default class Vector4 extends Float32Array implements Cloneable<Vector4> {
    constructor();
    constructor(vector: Vector2);
    constructor(vector?: Vector3);
    constructor(vector?: Vector4);
    constructor(array: Float32Array);
    constructor(array: Array<number>);
    constructor(list: List<number>);
    constructor(w: number, x: number, y: number, z: number);
    W: number;
    X: number;
    Y: number;
    Z: number;
    readonly Length: number;
    static Length(w?: Vector4 | Float32Array | Array<number> | List<number> | number, x?: number, y?: number, z?: number): number;
    readonly ZERO: Vector4;
    readonly ONE: Vector4;
    readonly UNIT: Vector4;
    Set(vector: Vector2): Vector4;
    Set(vector?: Vector3): Vector4;
    Set(vector?: Vector4): Vector4;
    Set(array: Float32Array): Vector4;
    Set(array: Array<number>): Vector4;
    Set(list: List<number>): Vector4;
    Set(w: number, x: number, y: number, z: number): Vector4;
    static Set(vector: Vector4, w: Vector2 | Vector3 | Vector4 | Float32Array | Array<number> | List<number> | number, x?: number, y?: number, z?: number): Vector4;
    Sum(w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): Vector4;
    static Sum(vector: Vector4, w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): Vector4;
    Diff(w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): Vector4;
    static Diff(vector: Vector4, w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): Vector4;
    Mult(w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): Vector4;
    static Mult(vector: Vector4, w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): Vector4;
    static Scale(vector: Vector4, scaler: number): Vector4;
    Dot(w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): number;
    static Dot(vector: Vector4, w?: Vector4 | Float32Array | number[] | number, x?: number, y?: number, z?: number): number;
    Unit(): Vector4;
    static Unit(vector: Vector4): Vector4;
    toString(): string;
    toLocaleString(): string;
    Clone(): Vector4;
}
